### ISSUE TITLE
Extra linebreaks during typing animation for headings

### ISSUE THREAD

**Issue by MattIPv4** [Hacktoberfest/hacktoberfest-2022#59]
## Information

- URL: https://hacktoberfest.com/
- Browser: Firefox Developer Edition 131.0b1 (aarch64)
- Operating System: macOS Sonoma 14.5
- Device: MacBook Pro 16" 2021 (M1)

### Description

At certain resolutions (observed at 1920x1080), the typing animation used on headings will sometimes result in an extra linebreak being rendered during the animation that disappears once the animation completes.

### Steps to reproduce

At 1920x1080, load the homepage.

https://github.com/user-attachments/assets/97989ff3-50c3-4706-83a4-d749cecaacdf

https://github.com/user-attachments/assets/6ef07b22-30e7-4891-a6be-80e90f40d29f

### Expected behavior

Animation does not interfere with how the heading text would naturally render.

**Comment by Thunder-Blaze** [comment]
@MattIPv4 Hello Sir, Can you please Assign this issue #59 to me under Hacktoberfest

**Comment by MattIPv4** [comment]
Sure
