### ISSUE TITLE
Bad/broken link to firstissue.dev on participation page

### ISSUE THREAD

**Issue by indiaaeevans** [Hacktoberfest/hacktoberfest-2022#62]
## Information

- URL: https://github.com/Hacktoberfest/hacktoberfest-2022/blob/main/src/lib/participation.js#L107
- Browser: N/A
- Operating System: N/A
- Device: N/A

### Description

the firstissue.dev site that is linked does not contain relevant content.

### Steps to reproduce

Go to [participation page](https://hacktoberfest.com/participation/#beginner-resources) and click on [Explore projects with issues on firstissue.dev](https://firstissue.dev/)

### Expected behavior

I'm guessing that the intended site for this link is actually [goodfirstissue.dev](https://goodfirstissue.dev/)

**Comment by MattIPv4** [comment]
Heh, I remember swapping this over last year as firstissue.dev was a newer/more up to date version of the same: https://web.archive.org/web/20231009163225/https://www.firstissue.dev/

Looks like since then the site has gone offline. Feel free to open a PR to switch it back :)
